### ISSUE TITLE
Problem with the database for week 3

### ISSUE THREAD

**Issue by Datadoulla** [ajstarks/dubois-data-portraits#6]
There are 3 problems with the week 3 database:
- the database does not have variable names, so when we import the data into software such as R without specifying this, the first line is read as the variable name.
- the second problem is on lines 12 and 14 (starting the count with 1) where the year 1888 is repeated twice instead of 1886 for line 12 and 1888 for line 14.
- problem 3 is on the original plate where it is specified that the bar for 1899 shows 1062223 acres whereas the data shows 1023741.4.

**Comment by ajstarks** [comment]
fixed.

**Comment by ajstarks** [comment]
Added headings
